# Generated by Django 3.2.15 on 2022-08-23 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../pexels-artem-podrez-7048043_jblpym', upload_to='images/')),
                ('music_medium', models.CharField(choices=[('none', 'None'), ('cassette', 'Cassette'), ('CD', 'CD'), ('minidisc', 'Minidisc'), ('mp3', 'mp3'), ('radio', 'Radio'), ('vinyl', 'Vinyl')], default='none', max_length=10)),
                ('song_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('beverage', models.CharField(choices=[('none', 'None'), ('water', 'Water'), ('juice', 'Juice'), ('soda', 'Soda'), ('tea', 'Tea'), ('coffee', 'Coffee'), ('wine', 'Wine'), ('beer', 'Beer'), ('cocktail', 'Cocktail'), ('spirits', 'Spirits')], default='none', max_length=10)),
                ('artistic_medium', models.CharField(choices=[('none', 'None'), ('acrylic_paint', 'Acrylic paint'), ('clay', 'Clay'), ('coding', 'Coding'), ('coloured_pencils', 'Coloured pencils'), ('digital', 'Digital'), ('glass', 'Glass'), ('markers', 'Markers'), ('metal', 'Metal'), ('oil_paint', 'Oil paint'), ('photography', 'Photography'), ('spray_paint', 'Spray paint'), ('videography', 'Videography'), ('water_colours', 'Water colours'), ('wood', 'Wood')], default='none', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
