# Generated by Django 3.2.15 on 2022-08-15 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../pexels-artem-podrez-7048043_jblpym', upload_to='images/')),
                ('image_filter', models.CharField(choices=[('_1977', '1977'), ('brannan', 'Brannan'), ('earlybird', 'Earlybird'), ('hudson', 'Hudson'), ('inkwell', 'Inkwell'), ('lofi', 'Lo-Fi'), ('kelvin', 'Kelvin'), ('normal', 'Normal'), ('nashville', 'Nashville'), ('rise', 'Rise'), ('toaster', 'Toaster'), ('valencia', 'Valencia'), ('walden', 'Walden'), ('xpro2', 'X-pro II')], default='normal', max_length=32)),
                ('music_medium', models.CharField(choices=[('cassette', 'Cassette'), ('CD', 'CD'), ('minidisc', 'Minidisc'), ('vinyl', 'Vinyl'), ('mp3', 'mp3'), ('radio', 'Radio'), ('none', 'None')], default='none', max_length=10)),
                ('song_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('beverage', models.CharField(choices=[('water', 'Water'), ('soda', 'Soda'), ('juice', 'Juice'), ('coffee', 'Coffee'), ('tea', 'Tea'), ('wine', 'Wine'), ('beer', 'Beer'), ('cocktail', 'Cocktail'), ('spirits', 'Spirits'), ('none', 'None')], default='none', max_length=10)),
                ('artistic_medium', models.CharField(choices=[('acrylic_paint', 'Acrylic paint'), ('oil_paint', 'Oil paint'), ('water_colours', 'Water colours'), ('spray_paint', 'Spray paint'), ('coloured_pencils', 'Coloured pencils'), ('markers', 'Markers'), ('photography', 'Photography'), ('videography', 'Videography'), ('digital', 'Digital'), ('coding', 'Coding'), ('wood', 'Wood'), ('clay', 'Clay'), ('metal', 'Metal'), ('glass', 'Glass'), ('none', 'None')], default='none', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
