# Generated by Django 3.2.15 on 2022-08-24 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, default='../pexels-artem-podrez-7048043_jblpym', upload_to='images/')),
                ('image_credit', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('entertainment', 'Entertainment'), ('events', 'Events'), ('in_depth', 'In-depth'), ('opinion', 'Opinion'), ('news', 'News')], default='news', max_length=55)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
