# Generated by Django 3.2.15 on 2022-08-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(choices=[('entertainment', 'Entertainment'), ('events', 'Events'), ('in_depth', 'In-depth'), ('opinion', 'Opinion'), ('news', 'News')], default='news', max_length=55)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
