# Generated by Django 3.2.15 on 2022-08-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('events', 'Events'), ('in_depth', 'In Depth'), ('opinion', 'Opinion'), ('news', 'News')], default='news', max_length=55),
        ),
    ]
